"""Generate bin/ wrappers for every [project.scripts] entry in pyproject.toml.

Each wrapper runs the command through `uv run --project <repo>`, so bin/ works from any directory without
activating the virtual environment. Wrappers are generated artifacts; edit [project.scripts] and rerun
`bin/gen-bin` (or `uv run gen-bin`) instead of editing them.
"""

import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
BIN_DIR = REPO_ROOT / "bin"
MARKER = "# Generated by gen-bin from [project.scripts] in pyproject.toml; do not edit."


def wrapper_text(command: str) -> str:
    return f'#!/bin/sh\n{MARKER}\nexec uv run --project "$(dirname "$0")/.." {command} "$@"\n'


def expected_wrappers() -> dict[str, str]:
    with (REPO_ROOT / "pyproject.toml").open("rb") as f:
        commands = tomllib.load(f)["project"]["scripts"]
    return {name: wrapper_text(name) for name in commands}


def main() -> None:
    BIN_DIR.mkdir(exist_ok=True)
    wrappers = expected_wrappers()
    for name, text in wrappers.items():
        path = BIN_DIR / name
        path.write_text(text, encoding="utf-8")
        path.chmod(0o755)
        print(path.relative_to(REPO_ROOT))
    for stale in BIN_DIR.iterdir():
        if stale.name not in wrappers and MARKER in stale.read_text(encoding="utf-8"):
            stale.unlink()
            print(f"removed {stale.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
